version: '3'
services:

  message-scheduler:
    container_name: message-scheduler
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    privileged: true
    ports:
      - '3000:3000'

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - 6379
